version: '3.9'

services:
  api-gateway:
    container_name: api-gateway
    build: ./
    networks:
      - dev-network
    ports:
      - ${API_GATEWAY_PORT}:${API_GATEWAY_PORT}
    env_file: 
      - .env
    depends_on:
      - otel_collector

  otel_collector:
    container_name: collector
    image: otel/opentelemetry-collector-contrib:latest
    command: --config=/etc/otel-collector-config.yaml
    volumes:
        - ./config/otel-collector-config.yaml:/etc/otel-collector-config.yaml
    ports:
      - 1888:1888 # pprof extension
      - 8888:8888 # Prometheus metrics exposed by the Collector
      - 8889:8889 # Prometheus exporter metrics
      - 13133:13133 # health_check extension
      - 4317:4317 # OTLP gRPC receiver
      - 4318:4318 # OTLP http receiver
      - 55679:55679 # zpages extension
    depends_on:
        - jaeger
    networks:
        - dev-network

  jaeger:
    container_name: jaeger
    image: jaegertracing/all-in-one:latest
    ports:
      - "16686:16686"
      - "14268"
      - "14250:14250"
      - "4317"                           # OTLP gRPC default port
      - "4318"
    environment:
      - COLLECTOR_OTLP_ENABLED=true
    networks:
        - dev-network

  # zipkin:
  #   container_name: zipkin
  #   image: openzipkin/zipkin:latest
  #   ports:
  #     - "9411:9411"

  # prometheus:
  #   container_name: prometheus
  #   image: prom/prometheus:latest
  #   command:
  #       - --config.file=/etc/prometheus/prometheus-config.yaml
  #   volumes:
  #       - ./config/prometheus-config.yaml:/etc/prometheus/prometheus-config.yaml
  #   ports:
  #       - "9090:9090"
  #   networks:
  #      - dev-network

networks:
  dev-network:
    driver: bridge