# Окружение - local, dev или prod
env: "local"

# конфигурация нашего posts-сервера
likes_server: 
  posts_port: "8082"
  
# конфигурация PostgresDB
postgres_likes_db: 
  user: ""
  password: ""
  host: "postgres_likes_db"
  port: 5432
  name: "postgres"
  ssl_mode: "disable"

# конфигурация gRPC сервера
grpc:
  likes_grpc_port: 13715