# Окружение - local, dev или prod
env: "local"

# конфигурация нашего posts-сервера
likes_server: 
  posts_port: 8082
  
# конфигурация PostgresDB
postgres_likes_db: 
  user: ""
  password: ""
  host: "localhost"
  port: 5434
  name: "postgres"
  ssl_mode: "disable"