// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v3.12.4
// source: likes/likes.proto

package golang

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateReactionRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PostId   string `protobuf:"bytes,1,opt,name=post_id,json=postId,proto3" json:"post_id,omitempty"`
	AuthorId string `protobuf:"bytes,2,opt,name=author_id,json=authorId,proto3" json:"author_id,omitempty"`
}

func (x *CreateReactionRequest) Reset() {
	*x = CreateReactionRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_likes_likes_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateReactionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateReactionRequest) ProtoMessage() {}

func (x *CreateReactionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_likes_likes_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateReactionRequest.ProtoReflect.Descriptor instead.
func (*CreateReactionRequest) Descriptor() ([]byte, []int) {
	return file_likes_likes_proto_rawDescGZIP(), []int{0}
}

func (x *CreateReactionRequest) GetPostId() string {
	if x != nil {
		return x.PostId
	}
	return ""
}

func (x *CreateReactionRequest) GetAuthorId() string {
	if x != nil {
		return x.AuthorId
	}
	return ""
}

type CreateReactionResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ReactionId string `protobuf:"bytes,1,opt,name=reaction_id,json=reactionId,proto3" json:"reaction_id,omitempty"`
}

func (x *CreateReactionResponse) Reset() {
	*x = CreateReactionResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_likes_likes_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateReactionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateReactionResponse) ProtoMessage() {}

func (x *CreateReactionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_likes_likes_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateReactionResponse.ProtoReflect.Descriptor instead.
func (*CreateReactionResponse) Descriptor() ([]byte, []int) {
	return file_likes_likes_proto_rawDescGZIP(), []int{1}
}

func (x *CreateReactionResponse) GetReactionId() string {
	if x != nil {
		return x.ReactionId
	}
	return ""
}

type GetReactionsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PostId string `protobuf:"bytes,1,opt,name=post_id,json=postId,proto3" json:"post_id,omitempty"`
	Limit  uint64 `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset uint64 `protobuf:"varint,3,opt,name=offset,proto3" json:"offset,omitempty"`
}

func (x *GetReactionsRequest) Reset() {
	*x = GetReactionsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_likes_likes_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetReactionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetReactionsRequest) ProtoMessage() {}

func (x *GetReactionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_likes_likes_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetReactionsRequest.ProtoReflect.Descriptor instead.
func (*GetReactionsRequest) Descriptor() ([]byte, []int) {
	return file_likes_likes_proto_rawDescGZIP(), []int{2}
}

func (x *GetReactionsRequest) GetPostId() string {
	if x != nil {
		return x.PostId
	}
	return ""
}

func (x *GetReactionsRequest) GetLimit() uint64 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *GetReactionsRequest) GetOffset() uint64 {
	if x != nil {
		return x.Offset
	}
	return 0
}

type GetReactionsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Reactions []*Reaction `protobuf:"bytes,1,rep,name=reactions,proto3" json:"reactions,omitempty"`
}

func (x *GetReactionsResponse) Reset() {
	*x = GetReactionsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_likes_likes_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetReactionsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetReactionsResponse) ProtoMessage() {}

func (x *GetReactionsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_likes_likes_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetReactionsResponse.ProtoReflect.Descriptor instead.
func (*GetReactionsResponse) Descriptor() ([]byte, []int) {
	return file_likes_likes_proto_rawDescGZIP(), []int{3}
}

func (x *GetReactionsResponse) GetReactions() []*Reaction {
	if x != nil {
		return x.Reactions
	}
	return nil
}

type Reaction struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ReactionId string `protobuf:"bytes,1,opt,name=reaction_id,json=reactionId,proto3" json:"reaction_id,omitempty"`
	AuthorId   string `protobuf:"bytes,2,opt,name=author_id,json=authorId,proto3" json:"author_id,omitempty"`
}

func (x *Reaction) Reset() {
	*x = Reaction{}
	if protoimpl.UnsafeEnabled {
		mi := &file_likes_likes_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Reaction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Reaction) ProtoMessage() {}

func (x *Reaction) ProtoReflect() protoreflect.Message {
	mi := &file_likes_likes_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Reaction.ProtoReflect.Descriptor instead.
func (*Reaction) Descriptor() ([]byte, []int) {
	return file_likes_likes_proto_rawDescGZIP(), []int{4}
}

func (x *Reaction) GetReactionId() string {
	if x != nil {
		return x.ReactionId
	}
	return ""
}

func (x *Reaction) GetAuthorId() string {
	if x != nil {
		return x.AuthorId
	}
	return ""
}

type DeleteReactionRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ReactionId string `protobuf:"bytes,1,opt,name=reaction_id,json=reactionId,proto3" json:"reaction_id,omitempty"`
	PostId     string `protobuf:"bytes,2,opt,name=post_id,json=postId,proto3" json:"post_id,omitempty"`
	AuthorId   string `protobuf:"bytes,4,opt,name=author_id,json=authorId,proto3" json:"author_id,omitempty"`
}

func (x *DeleteReactionRequest) Reset() {
	*x = DeleteReactionRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_likes_likes_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteReactionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteReactionRequest) ProtoMessage() {}

func (x *DeleteReactionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_likes_likes_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteReactionRequest.ProtoReflect.Descriptor instead.
func (*DeleteReactionRequest) Descriptor() ([]byte, []int) {
	return file_likes_likes_proto_rawDescGZIP(), []int{5}
}

func (x *DeleteReactionRequest) GetReactionId() string {
	if x != nil {
		return x.ReactionId
	}
	return ""
}

func (x *DeleteReactionRequest) GetPostId() string {
	if x != nil {
		return x.PostId
	}
	return ""
}

func (x *DeleteReactionRequest) GetAuthorId() string {
	if x != nil {
		return x.AuthorId
	}
	return ""
}

type DeleteReactionResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SuccessMessage string `protobuf:"bytes,1,opt,name=success_message,json=successMessage,proto3" json:"success_message,omitempty"`
}

func (x *DeleteReactionResponse) Reset() {
	*x = DeleteReactionResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_likes_likes_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteReactionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteReactionResponse) ProtoMessage() {}

func (x *DeleteReactionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_likes_likes_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteReactionResponse.ProtoReflect.Descriptor instead.
func (*DeleteReactionResponse) Descriptor() ([]byte, []int) {
	return file_likes_likes_proto_rawDescGZIP(), []int{6}
}

func (x *DeleteReactionResponse) GetSuccessMessage() string {
	if x != nil {
		return x.SuccessMessage
	}
	return ""
}

type GetReactionRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ReactionId string `protobuf:"bytes,1,opt,name=reaction_id,json=reactionId,proto3" json:"reaction_id,omitempty"`
}

func (x *GetReactionRequest) Reset() {
	*x = GetReactionRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_likes_likes_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetReactionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetReactionRequest) ProtoMessage() {}

func (x *GetReactionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_likes_likes_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetReactionRequest.ProtoReflect.Descriptor instead.
func (*GetReactionRequest) Descriptor() ([]byte, []int) {
	return file_likes_likes_proto_rawDescGZIP(), []int{7}
}

func (x *GetReactionRequest) GetReactionId() string {
	if x != nil {
		return x.ReactionId
	}
	return ""
}

type GetReactionResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ReactionId string `protobuf:"bytes,1,opt,name=reaction_id,json=reactionId,proto3" json:"reaction_id,omitempty"`
	AuthorId   string `protobuf:"bytes,2,opt,name=author_id,json=authorId,proto3" json:"author_id,omitempty"`
}

func (x *GetReactionResponse) Reset() {
	*x = GetReactionResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_likes_likes_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetReactionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetReactionResponse) ProtoMessage() {}

func (x *GetReactionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_likes_likes_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetReactionResponse.ProtoReflect.Descriptor instead.
func (*GetReactionResponse) Descriptor() ([]byte, []int) {
	return file_likes_likes_proto_rawDescGZIP(), []int{8}
}

func (x *GetReactionResponse) GetReactionId() string {
	if x != nil {
		return x.ReactionId
	}
	return ""
}

func (x *GetReactionResponse) GetAuthorId() string {
	if x != nil {
		return x.AuthorId
	}
	return ""
}

type DeleteReactionsByAuthorRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AuthorId string `protobuf:"bytes,1,opt,name=author_id,json=authorId,proto3" json:"author_id,omitempty"`
}

func (x *DeleteReactionsByAuthorRequest) Reset() {
	*x = DeleteReactionsByAuthorRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_likes_likes_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteReactionsByAuthorRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteReactionsByAuthorRequest) ProtoMessage() {}

func (x *DeleteReactionsByAuthorRequest) ProtoReflect() protoreflect.Message {
	mi := &file_likes_likes_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteReactionsByAuthorRequest.ProtoReflect.Descriptor instead.
func (*DeleteReactionsByAuthorRequest) Descriptor() ([]byte, []int) {
	return file_likes_likes_proto_rawDescGZIP(), []int{9}
}

func (x *DeleteReactionsByAuthorRequest) GetAuthorId() string {
	if x != nil {
		return x.AuthorId
	}
	return ""
}

type DeleteReactionsByAuthorResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SuccessMessage string `protobuf:"bytes,1,opt,name=success_message,json=successMessage,proto3" json:"success_message,omitempty"`
}

func (x *DeleteReactionsByAuthorResponse) Reset() {
	*x = DeleteReactionsByAuthorResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_likes_likes_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteReactionsByAuthorResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteReactionsByAuthorResponse) ProtoMessage() {}

func (x *DeleteReactionsByAuthorResponse) ProtoReflect() protoreflect.Message {
	mi := &file_likes_likes_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteReactionsByAuthorResponse.ProtoReflect.Descriptor instead.
func (*DeleteReactionsByAuthorResponse) Descriptor() ([]byte, []int) {
	return file_likes_likes_proto_rawDescGZIP(), []int{10}
}

func (x *DeleteReactionsByAuthorResponse) GetSuccessMessage() string {
	if x != nil {
		return x.SuccessMessage
	}
	return ""
}

type DeleteReactionsByPostRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PostId string `protobuf:"bytes,1,opt,name=post_id,json=postId,proto3" json:"post_id,omitempty"`
}

func (x *DeleteReactionsByPostRequest) Reset() {
	*x = DeleteReactionsByPostRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_likes_likes_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteReactionsByPostRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteReactionsByPostRequest) ProtoMessage() {}

func (x *DeleteReactionsByPostRequest) ProtoReflect() protoreflect.Message {
	mi := &file_likes_likes_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteReactionsByPostRequest.ProtoReflect.Descriptor instead.
func (*DeleteReactionsByPostRequest) Descriptor() ([]byte, []int) {
	return file_likes_likes_proto_rawDescGZIP(), []int{11}
}

func (x *DeleteReactionsByPostRequest) GetPostId() string {
	if x != nil {
		return x.PostId
	}
	return ""
}

type DeleteReactionsByPostResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SuccessMessage string `protobuf:"bytes,1,opt,name=success_message,json=successMessage,proto3" json:"success_message,omitempty"`
}

func (x *DeleteReactionsByPostResponse) Reset() {
	*x = DeleteReactionsByPostResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_likes_likes_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteReactionsByPostResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteReactionsByPostResponse) ProtoMessage() {}

func (x *DeleteReactionsByPostResponse) ProtoReflect() protoreflect.Message {
	mi := &file_likes_likes_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteReactionsByPostResponse.ProtoReflect.Descriptor instead.
func (*DeleteReactionsByPostResponse) Descriptor() ([]byte, []int) {
	return file_likes_likes_proto_rawDescGZIP(), []int{12}
}

func (x *DeleteReactionsByPostResponse) GetSuccessMessage() string {
	if x != nil {
		return x.SuccessMessage
	}
	return ""
}

var File_likes_likes_proto protoreflect.FileDescriptor

var file_likes_likes_proto_rawDesc = []byte{
	0x0a, 0x11, 0x6c, 0x69, 0x6b, 0x65, 0x73, 0x2f, 0x6c, 0x69, 0x6b, 0x65, 0x73, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x12, 0x05, 0x6c, 0x69, 0x6b, 0x65, 0x73, 0x22, 0x4d, 0x0a, 0x15, 0x43, 0x72,
	0x65, 0x61, 0x74, 0x65, 0x52, 0x65, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x17, 0x0a, 0x07, 0x70, 0x6f, 0x73, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x70, 0x6f, 0x73, 0x74, 0x49, 0x64, 0x12, 0x1b, 0x0a, 0x09,
	0x61, 0x75, 0x74, 0x68, 0x6f, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x08, 0x61, 0x75, 0x74, 0x68, 0x6f, 0x72, 0x49, 0x64, 0x22, 0x39, 0x0a, 0x16, 0x43, 0x72, 0x65,
	0x61, 0x74, 0x65, 0x52, 0x65, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x1f, 0x0a, 0x0b, 0x72, 0x65, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x5f,
	0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x72, 0x65, 0x61, 0x63, 0x74, 0x69,
	0x6f, 0x6e, 0x49, 0x64, 0x22, 0x5c, 0x0a, 0x13, 0x47, 0x65, 0x74, 0x52, 0x65, 0x61, 0x63, 0x74,
	0x69, 0x6f, 0x6e, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x17, 0x0a, 0x07, 0x70,
	0x6f, 0x73, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x70, 0x6f,
	0x73, 0x74, 0x49, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x6c, 0x69, 0x6d, 0x69, 0x74, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x04, 0x52, 0x05, 0x6c, 0x69, 0x6d, 0x69, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x6f, 0x66,
	0x66, 0x73, 0x65, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x04, 0x52, 0x06, 0x6f, 0x66, 0x66, 0x73,
	0x65, 0x74, 0x22, 0x45, 0x0a, 0x14, 0x47, 0x65, 0x74, 0x52, 0x65, 0x61, 0x63, 0x74, 0x69, 0x6f,
	0x6e, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x2d, 0x0a, 0x09, 0x72, 0x65,
	0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0f, 0x2e,
	0x6c, 0x69, 0x6b, 0x65, 0x73, 0x2e, 0x52, 0x65, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x09,
	0x72, 0x65, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x22, 0x48, 0x0a, 0x08, 0x52, 0x65, 0x61,
	0x63, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x1f, 0x0a, 0x0b, 0x72, 0x65, 0x61, 0x63, 0x74, 0x69, 0x6f,
	0x6e, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x72, 0x65, 0x61, 0x63,
	0x74, 0x69, 0x6f, 0x6e, 0x49, 0x64, 0x12, 0x1b, 0x0a, 0x09, 0x61, 0x75, 0x74, 0x68, 0x6f, 0x72,
	0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x61, 0x75, 0x74, 0x68, 0x6f,
	0x72, 0x49, 0x64, 0x22, 0x6e, 0x0a, 0x15, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x52, 0x65, 0x61,
	0x63, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1f, 0x0a, 0x0b,
	0x72, 0x65, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x0a, 0x72, 0x65, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x49, 0x64, 0x12, 0x17, 0x0a,
	0x07, 0x70, 0x6f, 0x73, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06,
	0x70, 0x6f, 0x73, 0x74, 0x49, 0x64, 0x12, 0x1b, 0x0a, 0x09, 0x61, 0x75, 0x74, 0x68, 0x6f, 0x72,
	0x5f, 0x69, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x61, 0x75, 0x74, 0x68, 0x6f,
	0x72, 0x49, 0x64, 0x22, 0x41, 0x0a, 0x16, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x52, 0x65, 0x61,
	0x63, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x27, 0x0a,
	0x0f, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x5f, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0e, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x4d,
	0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x22, 0x35, 0x0a, 0x12, 0x47, 0x65, 0x74, 0x52, 0x65, 0x61,
	0x63, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1f, 0x0a, 0x0b,
	0x72, 0x65, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x0a, 0x72, 0x65, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x49, 0x64, 0x22, 0x53, 0x0a,
	0x13, 0x47, 0x65, 0x74, 0x52, 0x65, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1f, 0x0a, 0x0b, 0x72, 0x65, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e,
	0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x72, 0x65, 0x61, 0x63, 0x74,
	0x69, 0x6f, 0x6e, 0x49, 0x64, 0x12, 0x1b, 0x0a, 0x09, 0x61, 0x75, 0x74, 0x68, 0x6f, 0x72, 0x5f,
	0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x61, 0x75, 0x74, 0x68, 0x6f, 0x72,
	0x49, 0x64, 0x22, 0x3d, 0x0a, 0x1e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x52, 0x65, 0x61, 0x63,
	0x74, 0x69, 0x6f, 0x6e, 0x73, 0x42, 0x79, 0x41, 0x75, 0x74, 0x68, 0x6f, 0x72, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x1b, 0x0a, 0x09, 0x61, 0x75, 0x74, 0x68, 0x6f, 0x72, 0x5f, 0x69,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x61, 0x75, 0x74, 0x68, 0x6f, 0x72, 0x49,
	0x64, 0x22, 0x4a, 0x0a, 0x1f, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x52, 0x65, 0x61, 0x63, 0x74,
	0x69, 0x6f, 0x6e, 0x73, 0x42, 0x79, 0x41, 0x75, 0x74, 0x68, 0x6f, 0x72, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x27, 0x0a, 0x0f, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x5f,
	0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0e, 0x73,
	0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x22, 0x37, 0x0a,
	0x1c, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x52, 0x65, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x73,
	0x42, 0x79, 0x50, 0x6f, 0x73, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x17, 0x0a,
	0x07, 0x70, 0x6f, 0x73, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06,
	0x70, 0x6f, 0x73, 0x74, 0x49, 0x64, 0x22, 0x48, 0x0a, 0x1d, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65,
	0x52, 0x65, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x42, 0x79, 0x50, 0x6f, 0x73, 0x74, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x27, 0x0a, 0x0f, 0x73, 0x75, 0x63, 0x63, 0x65,
	0x73, 0x73, 0x5f, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x0e, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65,
	0x42, 0x17, 0x5a, 0x15, 0x6c, 0x69, 0x6b, 0x65, 0x73, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x67,
	0x65, 0x6e, 0x2f, 0x67, 0x6f, 0x6c, 0x61, 0x6e, 0x67, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x33,
}

var (
	file_likes_likes_proto_rawDescOnce sync.Once
	file_likes_likes_proto_rawDescData = file_likes_likes_proto_rawDesc
)

func file_likes_likes_proto_rawDescGZIP() []byte {
	file_likes_likes_proto_rawDescOnce.Do(func() {
		file_likes_likes_proto_rawDescData = protoimpl.X.CompressGZIP(file_likes_likes_proto_rawDescData)
	})
	return file_likes_likes_proto_rawDescData
}

var file_likes_likes_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_likes_likes_proto_goTypes = []any{
	(*CreateReactionRequest)(nil),           // 0: likes.CreateReactionRequest
	(*CreateReactionResponse)(nil),          // 1: likes.CreateReactionResponse
	(*GetReactionsRequest)(nil),             // 2: likes.GetReactionsRequest
	(*GetReactionsResponse)(nil),            // 3: likes.GetReactionsResponse
	(*Reaction)(nil),                        // 4: likes.Reaction
	(*DeleteReactionRequest)(nil),           // 5: likes.DeleteReactionRequest
	(*DeleteReactionResponse)(nil),          // 6: likes.DeleteReactionResponse
	(*GetReactionRequest)(nil),              // 7: likes.GetReactionRequest
	(*GetReactionResponse)(nil),             // 8: likes.GetReactionResponse
	(*DeleteReactionsByAuthorRequest)(nil),  // 9: likes.DeleteReactionsByAuthorRequest
	(*DeleteReactionsByAuthorResponse)(nil), // 10: likes.DeleteReactionsByAuthorResponse
	(*DeleteReactionsByPostRequest)(nil),    // 11: likes.DeleteReactionsByPostRequest
	(*DeleteReactionsByPostResponse)(nil),   // 12: likes.DeleteReactionsByPostResponse
}
var file_likes_likes_proto_depIdxs = []int32{
	4, // 0: likes.GetReactionsResponse.reactions:type_name -> likes.Reaction
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_likes_likes_proto_init() }
func file_likes_likes_proto_init() {
	if File_likes_likes_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_likes_likes_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*CreateReactionRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_likes_likes_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*CreateReactionResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_likes_likes_proto_msgTypes[2].Exporter = func(v any, i int) any {
			switch v := v.(*GetReactionsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_likes_likes_proto_msgTypes[3].Exporter = func(v any, i int) any {
			switch v := v.(*GetReactionsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_likes_likes_proto_msgTypes[4].Exporter = func(v any, i int) any {
			switch v := v.(*Reaction); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_likes_likes_proto_msgTypes[5].Exporter = func(v any, i int) any {
			switch v := v.(*DeleteReactionRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_likes_likes_proto_msgTypes[6].Exporter = func(v any, i int) any {
			switch v := v.(*DeleteReactionResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_likes_likes_proto_msgTypes[7].Exporter = func(v any, i int) any {
			switch v := v.(*GetReactionRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_likes_likes_proto_msgTypes[8].Exporter = func(v any, i int) any {
			switch v := v.(*GetReactionResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_likes_likes_proto_msgTypes[9].Exporter = func(v any, i int) any {
			switch v := v.(*DeleteReactionsByAuthorRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_likes_likes_proto_msgTypes[10].Exporter = func(v any, i int) any {
			switch v := v.(*DeleteReactionsByAuthorResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_likes_likes_proto_msgTypes[11].Exporter = func(v any, i int) any {
			switch v := v.(*DeleteReactionsByPostRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_likes_likes_proto_msgTypes[12].Exporter = func(v any, i int) any {
			switch v := v.(*DeleteReactionsByPostResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_likes_likes_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_likes_likes_proto_goTypes,
		DependencyIndexes: file_likes_likes_proto_depIdxs,
		MessageInfos:      file_likes_likes_proto_msgTypes,
	}.Build()
	File_likes_likes_proto = out.File
	file_likes_likes_proto_rawDesc = nil
	file_likes_likes_proto_goTypes = nil
	file_likes_likes_proto_depIdxs = nil
}
