# Окружение - local, dev или prod
env: "local"

# конфигурация gatewayGRPCServer
gatewayGRPCServer: 
  api_gateway_port: "8000"
  auth_server_address: "auth:13713"
  posts_server_address: "posts:13714"
  likes_server_address: "likes:13715"

# конфигурация JWT
jwt_config:
  path_private_key: ""
  path_public_key: ""
  access_token_exp: 60
  refresh_token_exp: 60
  session_cookie_name: ""

# jaeger
jaeger:
  server_name: "MicroserviseGo"
  collector_url: "otel_collector:4317"
  application: "Api-Gateway"