basePath: /api/v1
definitions:
  schemas.CommentCreateRequest:
    properties:
      text:
        type: string
    type: object
  schemas.CommentResponse:
    properties:
      author_id:
        type: string
      id:
        type: string
      text:
        type: string
    type: object
  schemas.CommentUpdateRequest:
    properties:
      text:
        type: string
    type: object
  schemas.ErrorResponse:
    properties:
      message:
        type: string
    type: object
  schemas.PostCreateRequest:
    properties:
      content:
        type: string
      title:
        type: string
    type: object
  schemas.PostResponse:
    properties:
      author_id:
        type: string
      comments:
        items:
          $ref: '#/definitions/schemas.CommentResponse'
        type: array
      content:
        type: string
      created_at:
        type: string
      id:
        type: string
      title:
        type: string
    type: object
  schemas.PostUpdateRequest:
    properties:
      content:
        type: string
      title:
        type: string
    type: object
  schemas.PostUpdatedResponse:
    properties:
      author_id:
        type: string
      content:
        type: string
      created_at:
        type: string
      id:
        type: string
      title:
        type: string
    type: object
  schemas.SuccessResponse:
    properties:
      message:
        type: string
    type: object
host: localhost:8081
info:
  contact:
    email: fvi-it@mail.ru
    name: Идель Фазлетдинов
  description: API-интерфейс службы управления постами и комментариями в Go с использованием
    платформы Gin framework.
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  title: Gin Posts Service
  version: "1.0"
paths:
  /post:
    post:
      consumes:
      - application/json
      parameters:
      - description: Создание Post
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/schemas.PostCreateRequest'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/schemas.SuccessResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/schemas.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/schemas.ErrorResponse'
      summary: Создание Post
      tags:
      - Posts
  /post/{post_id}:
    delete:
      consumes:
      - application/json
      parameters:
      - description: Post ID
        in: path
        name: post_id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "204":
          description: No Content
          schema:
            $ref: '#/definitions/schemas.SuccessResponse'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/schemas.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/schemas.ErrorResponse'
      summary: Удаление Post
      tags:
      - Posts
    get:
      consumes:
      - application/json
      parameters:
      - description: Post ID
        in: path
        name: post_id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/schemas.PostResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/schemas.ErrorResponse'
      summary: Получение Post
      tags:
      - Posts
    put:
      consumes:
      - application/json
      parameters:
      - description: Post ID
        in: path
        name: post_id
        required: true
        type: string
      - description: Для обновления Post
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/schemas.PostUpdateRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/schemas.PostUpdatedResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/schemas.ErrorResponse'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/schemas.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/schemas.ErrorResponse'
      summary: Обновление Post
      tags:
      - Posts
  /post/{post_id}/comment:
    post:
      consumes:
      - application/json
      parameters:
      - description: Post ID
        in: path
        name: post_id
        required: true
        type: string
      - description: Создание Comment
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/schemas.CommentCreateRequest'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/schemas.SuccessResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/schemas.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/schemas.ErrorResponse'
      summary: Создание Comment
      tags:
      - Comment
  /post/{post_id}/comment/{comment_id}:
    delete:
      consumes:
      - application/json
      parameters:
      - description: Post ID
        in: path
        name: post_id
        required: true
        type: string
      - description: Comment ID
        in: path
        name: comment_id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "204":
          description: No Content
          schema:
            $ref: '#/definitions/schemas.SuccessResponse'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/schemas.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/schemas.ErrorResponse'
      summary: Удаление Comment
      tags:
      - Comment
    get:
      consumes:
      - application/json
      parameters:
      - description: Post ID
        in: path
        name: post_id
        required: true
        type: string
      - description: Comment ID
        in: path
        name: comment_id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/schemas.CommentResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/schemas.ErrorResponse'
      summary: Получение Comment
      tags:
      - Comment
    put:
      consumes:
      - application/json
      parameters:
      - description: Post ID
        in: path
        name: post_id
        required: true
        type: string
      - description: Comment ID
        in: path
        name: comment_id
        required: true
        type: string
      - description: Для обновления Post
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/schemas.CommentUpdateRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/schemas.SuccessResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/schemas.ErrorResponse'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/schemas.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/schemas.ErrorResponse'
      summary: Обновление Comment
      tags:
      - Comment
  /post/{post_id}/comments:
    get:
      consumes:
      - application/json
      parameters:
      - description: Post ID
        in: path
        name: post_id
        required: true
        type: string
      - description: limit
        in: query
        name: limit
        required: true
        type: integer
      - description: offset
        in: query
        name: offset
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/schemas.CommentResponse'
            type: array
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/schemas.ErrorResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/schemas.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/schemas.ErrorResponse'
      summary: Получение списока Comment
      tags:
      - Comment
  /posts:
    get:
      consumes:
      - application/json
      parameters:
      - description: limit
        in: query
        name: limit
        required: true
        type: integer
      - description: offset
        in: query
        name: offset
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/schemas.PostResponse'
            type: array
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/schemas.ErrorResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/schemas.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/schemas.ErrorResponse'
      summary: Получение списока Post
      tags:
      - Posts
swagger: "2.0"
