# Окружение - local, dev или prod
env: "local"

# конфигурация auth service
auth_server: 
  auth_port: "8080"

# конфигурация JWT
jwt_config:
  path_private_key: ""
  path_public_key: ""
  access_token_exp: 60
  refresh_token_exp: 60
  session_cookie_name: ""
  
# конфигурация PostgresDB
postgres_auth_db: 
  user: ""
  password: ""
  host: "postgres_auth_db"
  port: 5432
  name: "postgres"
  ssl_mode: "disable"

# конфигурация MongoDB
mongo_auth_db:
  user: ""     
  password: "" 
  port: 27016
  host: "mongo_auth_db"     
  ctxExp: 10

grpc:
  auth_grpc_port: 13713
  timeout: 10h

# jaeger
jaeger:
  server_name: "MicroserviseGo"
  collector_url: "otel_collector:4317"
  application: "Auth"