basePath: /api/v1
definitions:
  schemas.ErrorResponse:
    properties:
      message:
        type: string
    type: object
  schemas.ReactionCreateRequest:
    properties:
      author_id:
        type: string
    type: object
  schemas.ReactionResponse:
    properties:
      author_id:
        type: string
      id:
        type: string
      post_id:
        type: string
    type: object
  schemas.SuccessResponse:
    properties:
      message:
        type: string
    type: object
host: localhost:8082
info:
  contact:
    email: fvi-it@mail.ru
    name: Идель Фазлетдинов
  description: API-интерфейс службы управления реакциями на посты в Go с использованием
    платформы Gin framework.
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  title: Gin Posts Service
  version: "1.0"
paths:
  /post/{post_id}/reaction:
    delete:
      consumes:
      - application/json
      parameters:
      - description: Post ID
        in: path
        name: post_id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "204":
          description: No Content
          schema:
            $ref: '#/definitions/schemas.SuccessResponse'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/schemas.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/schemas.ErrorResponse'
      summary: Удаление Reaction
      tags:
      - Reaction
    post:
      consumes:
      - application/json
      parameters:
      - description: Post ID
        in: path
        name: post_id
        required: true
        type: string
      - description: Создание Reaction
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/schemas.ReactionCreateRequest'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/schemas.SuccessResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/schemas.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/schemas.ErrorResponse'
      summary: Создание Reaction
      tags:
      - Reaction
  /post/{post_id}/reactions:
    get:
      consumes:
      - application/json
      parameters:
      - description: Post ID
        in: path
        name: post_id
        required: true
        type: string
      - description: limit
        in: query
        name: limit
        required: true
        type: integer
      - description: offset
        in: query
        name: offset
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/schemas.ReactionResponse'
            type: array
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/schemas.ErrorResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/schemas.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/schemas.ErrorResponse'
      summary: Получение списока Reactin на Post
      tags:
      - Reaction
swagger: "2.0"
