# Окружение - local, dev или prod
env: "local"

# конфигурация нашего posts-сервера
posts_server: 
  posts_port: "8081"
  
# конфигурация PostgresDB
postgres_posts_db: 
  user: ""
  password: ""
  host: "postgres_posts_db"
  port: 5432
  name: "postgres"
  ssl_mode: "disable"

# конфигурация RedisDB
redis_posts_db:
  host: "redis_posts_db"
  port: 6379
  exp: 60

clients:
  address: "localhost:13713"

grpc:
  posts_grpc_port: 13714