version: '3.9'

x-def-logging: &default-logging
  logging:
    # Указываем, какой драйвер использовать
    driver: "loki"
    options:
      loki-url: "http://localhost:3100/loki/api/v1/push"
      loki-batch-size: "100"
      loki-retries: 2
      loki-max-backoff: 1000ms
      loki-timeout: 1s

services:

  postgres_posts_db:
    container_name: postgres_posts_db
    image: postgres:15-alpine
    <<: *default-logging
    volumes:
      - pg-posts-data:/var/lib/postgresql/data
    networks:
      - dev-network
    env_file:
      - .env
    ports:
      - "5433:5432"

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      start_period: 30s
      interval: 30s
      timeout: 30s
      retries: 3

  redis_posts_db:
    container_name: redis_posts_db
    image: redis:latest
    <<: *default-logging
    command: --port ${REDIS_PORT}
    volumes:
      - redis-posts-data:/data
    networks:
      - dev-network
    env_file:
      - .env

    healthcheck:
      test: ["CMD-SHELL", "redis-cli ping | grep PONG"]
      interval: 30s
      timeout: 15s
      retries: 5

  posts:
    container_name: posts
    build: ./
    <<: *default-logging
    networks:
      - dev-network
    expose:
      - ${POSTS_GRPC_PORT}
    depends_on:
      postgres_posts_db:
        condition: service_healthy
        restart: true
      redis_posts_db:
        condition: service_healthy
    env_file: 
      - .env

volumes:
  pg-posts-data:
  redis-posts-data:

networks:
  dev-network:
    name: api-gateway_dev-network
    external: true