version: '3.9'

services:

  postgres_posts_db:
    container_name: postgres_posts_db
    image: postgres:15-alpine
    volumes:
      - pg-posts-data:/var/lib/postgresql/data
    ports:
      - ${POSTGRES_PORT}:5432
    networks:
      - dev-network
    env_file:
      - .env

  redis_posts_db:
    container_name: redis_posts_db
    image: redis:latest
    command: --port ${REDIS_PORT}
    ports:
      - ${REDIS_PORT}:${REDIS_PORT}
    volumes:
      - redis-posts-data:/data
    networks:
      - dev-network
    env_file:
      - .env

volumes:
  pg-posts-data:
  redis-posts-data:

networks:
  dev-network:
    name: auth_dev-network
    external: true